version: "3.8"
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC+2
    volumes:
      - ./config:/config
      - ../medias:/downloads
    ports:
      - 8000:8000
    restart: unless-stopped